{"changes": {"state": {"new": "open", "old": "resolved"}}, "links": {"self": {"href": "data/repositories/ignitionrobotics/ign-math/issues/78/changes/39962243.json"}, "html": {"href": "#!/ignitionrobotics/ign-math/issues/78#comment-39962243"}}, "issue": {"links": {"self": {"href": "data/repositories/ignitionrobotics/ign-math/issues/78.json"}}, "type": "issue", "id": 78, "repository": {"links": {"self": {"href": "data/repositories/ignitionrobotics/ign-math.json"}, "html": {"href": "#!/ignitionrobotics/ign-math"}, "avatar": {"href": "data/bytebucket.org/ravatar/{18503e50-08ea-4d88-ab99-110fde3c7256}ts=1533305"}}, "type": "repository", "name": "ign-math", "full_name": "ignitionrobotics/ign-math", "uuid": "{18503e50-08ea-4d88-ab99-110fde3c7256}"}, "title": "Frustum incorrectly reports that it contains a box"}, "created_on": "2017-09-19T16:31:14.114946+00:00", "user": {"display_name": "Shane Loretz", "uuid": "{656e3311-aad9-45a1-aaf7-b0ee0e84b287}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B656e3311-aad9-45a1-aaf7-b0ee0e84b287%7D"}, "html": {"href": "https://bitbucket.org/%7B656e3311-aad9-45a1-aaf7-b0ee0e84b287%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:684383ab-ac95-4859-a350-4a6f41a94a22/c7a1ebf5-cade-4115-9f26-9d3facb776db/128"}}, "nickname": "Shane Loretz", "type": "user", "account_id": "557058:684383ab-ac95-4859-a350-4a6f41a94a22"}, "message": {"raw": "Reopen, commit mistakenly closed. I thought the auto close only happened once a commit made it to the default branch? Or is that just a github thing?", "markup": "markdown", "html": "<p>Reopen, commit mistakenly closed. I thought the auto close only happened once a commit made it to the default branch? Or is that just a github thing?</p>", "type": "rendered"}, "type": "issue_change", "id": 39962243}