{"priority": "major", "kind": "bug", "repository": {"links": {"self": {"href": "data/repositories/ignitionrobotics/ign-transport.json"}, "html": {"href": "#!/ignitionrobotics/ign-transport"}, "avatar": {"href": "data/bytebucket.org/ravatar/{4249390a-7f55-404b-990d-817ba94cc7ac}ts=1533306"}}, "type": "repository", "name": "ign-transport", "full_name": "ignitionrobotics/ign-transport", "uuid": "{4249390a-7f55-404b-990d-817ba94cc7ac}"}, "links": {"attachments": {"href": "data/repositories/ignitionrobotics/ign-transport/issues/71/attachments_page=1.json"}, "self": {"href": "data/repositories/ignitionrobotics/ign-transport/issues/71.json"}, "watch": {"href": "https://api.bitbucket.org/2.0/repositories/ignitionrobotics/ign-transport/issues/71/watch"}, "comments": {"href": "data/repositories/ignitionrobotics/ign-transport/issues/71/comments_page=1.json"}, "html": {"href": "#!/ignitionrobotics/ign-transport/issues/71/exception-sending-message-in-docker"}, "vote": {"href": "https://api.bitbucket.org/2.0/repositories/ignitionrobotics/ign-transport/issues/71/vote"}}, "reporter": {"display_name": "Hamza Merzi\u0107", "uuid": "{2100f54d-6bc6-4db0-ada5-db7be9320606}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B2100f54d-6bc6-4db0-ada5-db7be9320606%7D"}, "html": {"href": "https://bitbucket.org/%7B2100f54d-6bc6-4db0-ada5-db7be9320606%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:172a2e1e-2bf2-4054-9b9b-9d541ddc8e4e/ab842f18-c8ca-4a0c-a82a-6d4d39ffdb37/128"}}, "nickname": "hamzaethz", "type": "user", "account_id": "557058:172a2e1e-2bf2-4054-9b9b-9d541ddc8e4e"}, "title": "Exception sending message in Docker", "component": null, "votes": 0, "watches": 1, "content": {"raw": "I have a setup where I use ignition transport to communicate between two nodes. The only communication that I use is services, in a manner that node1 is a client and node2 is a server for each service (sort of master-slave). The server is running gazebo simulation (gazebo 8), while the client is controlling the simulation through service calls. \r\n\r\nWhen I run this setup locally, it works without any issues. But when I run it in Docker, the program quite often crashes because the timeout is passed. The error message that I am getting is simply a wall of:\r\n\r\n\r\n```\r\n#!\r\n\r\nException sending a message\r\nException sending a message\r\nException sending a message\r\nException sending a message\r\nException sending a message\r\nException sending a message\r\nException sending a message\r\n...\r\n```\r\n\r\nAny idea why this could be the case? I am also running multiple simulations at the same time, i.e. multiple Docker containers with the same simulation (on the same machine), which might be the cause of some network issues?", "markup": "markdown", "html": "<p>I have a setup where I use ignition transport to communicate between two nodes. The only communication that I use is services, in a manner that node1 is a client and node2 is a server for each service (sort of master-slave). The server is running gazebo simulation (gazebo 8), while the client is controlling the simulation through service calls. </p>\n<p>When I run this setup locally, it works without any issues. But when I run it in Docker, the program quite often crashes because the timeout is passed. The error message that I am getting is simply a wall of:</p>\n<div class=\"codehilite\"><pre><span></span>Exception sending a message\nException sending a message\nException sending a message\nException sending a message\nException sending a message\nException sending a message\nException sending a message\n...\n</pre></div>\n\n\n<p>Any idea why this could be the case? I am also running multiple simulations at the same time, i.e. multiple Docker containers with the same simulation (on the same machine), which might be the cause of some network issues?</p>", "type": "rendered"}, "assignee": null, "state": "resolved", "version": null, "edited_on": null, "created_on": "2017-09-26T10:27:19.068820+00:00", "milestone": null, "updated_on": "2017-09-29T09:15:38.160255+00:00", "type": "issue", "id": 71}